Migration to update parent
beyondessential/tupaia pull request #1288
Opened 2020-09-09 02:08 UTC by Alastair-L

### Issue #:
https://github.com/beyondessential/tupaia-backlog/issues/1078

Screenshot here: https://github.com/beyondessential/tupaia-backlog/issues/1078#issuecomment-689253375

2020-09-09 02:20 UTC, kael89 approved these changes

2020-09-10 02:35 UTC, edmofro requested changes
This doesn't match my understanding of the structure of permissions... let's talk on Slack

2020-09-10 04:10 UTC, edmofro commented
See updates in the original card @Alastair-L

2020-09-10 21:14 UTC, edmofro approved these changes

2020-09-10 21:16 UTC, merged