Convert mocha to jest and parameterised it.
beyondessential/tupaia pull request #1375
Opened 2020-09-23 02:25 UTC by billli0

### Issue #:
[1271- Use a single test framework : **access-policy module only**](https://github.com/beyondessential/tupaia-backlog/issues/1271)

This branch is a draft PR for tracking the changes.

2020-09-23 05:28 UTC, billli0 commented
I'll adjust a few points to stick with the testing standard.

2020-09-24 03:50 UTC, kael89 commented on packages/access-policy/scripts/JestTransformer.js
> +});
Let's try defining this under the monorepo root, and importing it where required! No need to do this in this PR though, let's submit another PR for that

2020-09-24 04:58 UTC, kael89 requested changes
Great work! A few details here and there, but looking good overall!

2020-09-24 04:58 UTC, kael89 commented on packages/access-policy/src/__tests__/AccessPolicy.test.js
> +      it.each(testData)('%s', (_, arr, expected) => {
```suggestion
      it.each(testData)('%s', (_, entities, expected) => {
```

And in the line below

2020-09-24 04:58 UTC, kael89 commented on packages/access-policy/src/__tests__/AccessPolicy.test.js
> +    it('should return all permission groups when no entities are specified', () => {
This test case can be consolidated with the parameterized tests below:

```js
[
  'should return all permission groups when no entities are specified',
  undefined,
  ['Public', 'Admin', 'Royal Australasian College of Surgeons'],
],
```

2020-09-24 04:58 UTC, kael89 commented on packages/access-policy/src/__tests__/AccessPolicy.test.js
> +    describe('should return just the permission groups that relate to the provided entities', () => {
And then we can delete this describe block (using its description in the parameterized test cases below)

2020-09-24 04:58 UTC, kael89 commented on packages/access-policy/src/__tests__/AccessPolicy.test.js
> +        ['should not allow access with no entity', [], false],
We also need one test case for `undefined`

```suggestion
        ['should not allow access with no entity', [], false],
        ['should not allow access with no entity', undefined, false],
```

This corresponds to the following test case in the existing code:

```js
expect(accessPolicy.allowsSome()).to.equal(false);
```

2020-09-24 05:25 UTC, billli0 commented on packages/access-policy/src/__tests__/AccessPolicy.test.js
> +      ['should not allow access with no entity', ['', ''], false],
I put that in` line 82`. Hope that is correct.

2020-09-24 05:26 UTC, billli0 commented on packages/access-policy/src/__tests__/AccessPolicy.test.js
> +      ['should not allow access with no entity', ['', ''], false],
> One case is missing here. Existing code:
> 
> ```js
>     it('should allow access to a permission group that includes spaces', () => {
>       expect(accessPolicy.allows('SB', 'Royal Australasian College of Surgeons')).to.equal(true);
>     });
> ```

I put that in line 82. Hope that is correct.

2020-09-24 05:32 UTC, kael89 commented on packages/access-policy/src/__tests__/AccessPolicy.test.js
> +      ['should not allow access with no entity', ['', ''], false],
This uses `accessPolicy.allows`, while in line 82 it uses `accessPolicy.allowsSome`. Both cases are required

2020-09-24 05:35 UTC, billli0 commented on packages/access-policy/src/__tests__/AccessPolicy.test.js
> +      ['should not allow access with no entity', ['', ''], false],
> This uses `accessPolicy.allows`, while in line 82 it uses `accessPolicy.allowsSome`. Both cases are required

You are right. My bad. I'll add that.

2020-09-24 05:37 UTC, kael89 commented on packages/access-policy/src/__tests__/AccessPolicy.test.js
> +      ['should not allow access with no entity', ['', ''], false],
No worries! 😃

2020-09-24 06:38 UTC, kael89 commented on packages/access-policy/src/__tests__/AccessPolicy.test.js
> +    it.each(testDatas)('%s', (_, testData) => {
```suggestion
    it.each(testData)('%s', (_, testCaseData) => {
```

(You'll have to rename the corresponding vars in this block accordingly)

2020-09-24 06:38 UTC, kael89 approved these changes
Nice one! Just a detail, but pre-approving

2020-09-24 06:42 UTC, billli0 commented
> Nice one! Just a detail, but pre-approving

Awesome! I will merge it after test pass.

2020-09-24 06:45 UTC, kael89 commented
@billli0 good call, we can merge this directly because only tests were affected (no production code)

2020-09-24 11:12 UTC, merged