1354 display more useful error message on login for nonvalidated emai…
beyondessential/tupaia pull request #1460
Opened 2020-10-08 05:21 UTC by avaek

Addresses: https://github.com/beyondessential/tupaia-backlog/issues/1354

To be honest I'm not sure what a reducer is - making this one line change to this file seemed to fix the issue (from the perspective of the front end) but I'm not sure if I have to change things in other places too

Basically this change means that the error message that is displayed to the front end comes from the error supplied by the Authenticator package (rather than the hardcoded string that it used to display)

2020-10-08 06:58 UTC, Alastair-L commented
Hey @avaek, I do like this change! However, I have 2 possible improvements to it (but first a quick background on redux):

**Reducers** and **actions** are both concepts from redux, which is the framework that we use to control all the global storage in the frontend. 

In redux, the ONLY way that **state** can be changed is through the specific reducer that controls that piece of state. In this case, the piece of state `loginFailedMessage` is controlled by the `authentication` reducer (and you would access it with `authentication.loginFailedMessage`).

The only time reducers themselves are called is when **actions** are **dispatched**. In this case, there are 2 actions that can cause  `loginFailedMessage` to change: 
"OPEN_USER_DIALOG" and "ATTEMPT_LOGIN", which set it to `null`
"FETCH_LOGIN_ERROR". which you are familiar with, and
"FETCH_EMAIL_VERIFY_ERROR", which is called **after** clicking on the verify email link and is therefore no use to us.

On the action side of things, we can see the action `fetchUserLoginError` has the type 'FETCH_LOGIN_ERROR', and therefore will trigger our case whenever it is called.

Note: WHENEVER an action is dispatched, ALL reducers are called. It is the switch on action.type that determines which ones change (not relevant here, just might help understanding what is going on).

If you don't have [redux dev tools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd) yet, I would highly recommend getting them and having a little explore.

More in depth tutorial about redux [here](https://www.tutorialspoint.com/redux/redux_quick_guide.htm)



Now on to my suggestions:
1.  The FETCH_LOGIN_ERROR action already has an `errorMessage` key, which at the moment is not used. I would suggest removing that key (although it isn't really your fault, just a small code cleanup)
2. I would also like to see a default message in case `errors` is not defined or it has no key called `error`. Perhaps "Unknown error during login", or something.
3. I noticed that `errors` is not actually an array, although it is initialized to be one (see the start of `authentication`) and it's name suggests that it should be. I believe that we could solve this as part of this PR as well (this one is optional for me, but it wouldn't hurt to at least add a comment noting it).

2020-10-09 02:30 UTC, avaek commented
@Alastair-L - many thanks for that thorough review!

I think your idea about solving this in `sagas.js` is a really great idea because in addition to solving this card it also solves another one for free ( https://github.com/beyondessential/tupaia-backlog/issues/1355 )

I reverted my previous change but still performed the code cleanup you mentioned since I think this is still okay, is that still the right thing to do?

Also I'm not quite sure why the line in `sagas.js` was written the way it was but I just changed it from `details` to `error` like you mentioned because I assume it was written this way for a specific reason (I mostly don't understand why it was written `if (errorMessage.details && errorMessage.details === 'Email address not yet verified')` instead of just writing `if (errorMessage.details === 'Email address not yet verified')` but I'm sure there's a reason for this)

2020-10-09 03:31 UTC, Alastair-L requested changes
Nice work, and absolutely that `errorMessage` key is still unused!

I expect that there is probably a more robust way of handling this (maybe using error codes rather that the message) and explicitly handling more possible errors such as "User not found" (search `getAuthenticatedUser` in the auth package). However, I think that's out of scope for this issue.

Just that one small suggestion, then looks good 👍

2020-10-09 03:34 UTC, kael89 commented on packages/web-frontend/src/sagas.js
> +    if (errorMessage.error && errorMessage.error === 'Email address not yet verified') {
`?.` will work, go for it! `errorMessage && errorMessage.error` is also fine

2020-10-12 22:20 UTC, Alastair-L approved these changes
LGTM! Nice work.

2020-10-19 02:31 UTC, merged