1247 Add PSSS project and attach countries list with alternative hierarchy
beyondessential/tupaia pull request #1568
Opened 2020-11-04 01:04 UTC by EMcQ-BES

### Issue #: https://github.com/beyondessential/tupaia-backlog/issues/1247

### Changes:

- Add a migration file for creating PSSS project

2020-11-04 04:12 UTC, edmofro requested changes
Code all lgtm, with one suggested rename. I'm wondering about adding a country through a migration rather than through the admin panel process of creating a country then importing entities (of just that country) through the admin panel though. That admin panel process has some side effects, such as grabbing the geojson for the country from and adding that to the database.

So, please change this to assume NZ exists, and then add a data steward task to add it through the admin panel.

An additional complexity: this would then be an example of a migration relying on something existing in the database that doesn't exist on the end to end test instance (frozen a while ago, so won't have NZ). So please also add the first case of graceful error handling if we're on the e2e instance. How do you know that? Not sure.

2020-11-04 04:12 UTC, edmofro commented on packages/database/src/migrations/20201103092344-AddPSSSProject-modifies-data.js
> +    name: DASHBOARDGROUP_NAME,
Kinda weird variable name to use here. It is the same though, so maybe just a variable rename?

2020-11-05 00:42 UTC, EMcQ-BES commented
> So, please change this to assume NZ exists, and then add a data steward task to add it through the admin panel.

Edwin touched base with my via slack to confirm we can instead leave NZ off the list of countries for now. So I've removed it completely instead.

2020-11-05 01:00 UTC, edmofro approved these changes

2020-11-05 01:34 UTC, merged