Bugfixes: GET User Permissions
beyondessential/tupaia pull request #1749
Opened 2020-12-02 22:26 UTC by EMcQ-BES

### Issue #: https://github.com/beyondessential/tupaia-backlog/issues/1132

### Changes:

- Fixup column handling to use resource/record conversion
- Add missing endpoint for user/id/userEntityPermission
- Fully justify table names in permission filters

2020-12-02 23:12 UTC, kael89 requested changes
Looks great overall @EMcQ-BES ! Just one small suggestion

2020-12-02 23:12 UTC, kael89 commented on packages/meditrak-server/src/routes/GETSurveyScreenComponents/assertSurveyScreenComponentPermissions.js
> +    };
This way you can still use a `const` in line 37 above, and it's a bit simpler

```suggestion
    dbConditions['survey_screen.survey_id'] = surveyId;
```

Unless if you expect that a `survey_screen.survey_id` may exist in `criteria`, and if it exists you want it to take precedence over the `surveyId` value

2020-12-02 23:12 UTC, kael89 commented on packages/meditrak-server/src/routes/GETSurveyScreenComponents/assertSurveyScreenComponentPermissions.js
> +      ...criteria,
Same as above

2020-12-02 23:13 UTC, kael89 commented
@EMcQ-BES  There's also a failing unit test

2020-12-03 21:36 UTC, EMcQ-BES commented
> @EMcQ-BES There's also a failing unit test

Unit test was failing because of filters overwriting each other, I've added a function to merge filters together

2020-12-03 23:24 UTC, kael89 commented on packages/meditrak-server/src/routes/utilities/mergeFilter.js
> +export function mergeFilter(baseFilter, filterToMerge) {
Nice util!

2020-12-03 23:25 UTC, kael89 approved these changes
Looks good!

2020-12-03 23:29 UTC, merged