1364 stock status for non msupply countries
beyondessential/tupaia pull request #1839
Opened 2020-12-16 02:20 UTC by billli0

### Issue #:
[1364: 3 dashboard reports for UNFPA (Stock status for non mSupply countries)](https://github.com/beyondessential/tupaia-backlog/issues/1364)

### Changes:

- Add `tableOfCalculatedValuesForOrgUnits.js` data builder to build columns from organisation units with `tableOfCalculatedValues` data builder.
- Migration for adding three reports
- Make matching filter dynamic in `calculateOperationForAnalytics.js`
- Refactor code in `tableOfValuesForOrgUnits.js` and `tableOfDataValues.js`
- add function for row and column summary in matrix table (`addSummaryToTable.js`)

2020-12-21 08:19 UTC, kael89 requested changes
I have the impression that the code as is will not calculate correct percentages for `RH Products Stock Availability (HFRSA and Spot Check Survey Data) With Percentage`

2020-12-21 08:19 UTC, kael89 commented on packages/web-config-server/src/apiV1/dataBuilders/helpers/calculateOperationForAnalytics.js
> +  });
`Object.fromEntries` is often handy when creating value maps:

```suggestion
const valuesByFilterKey = Object.fromEntries(filterOptions.map(key => [key, config[key]]));
```

2020-12-21 08:30 UTC, kael89 requested changes

2020-12-21 08:30 UTC, kael89 commented on packages/web-config-server/src/apiV1/dataBuilders/generic/table/tableOfDataValues/addSummaryToTable.js
> +  const newColumnKey = 'rowSummary';
```suggestion
  const summaryColumnKey = 'rowSummary';
```

2020-12-21 08:30 UTC, kael89 commented on packages/web-config-server/src/apiV1/dataBuilders/generic/table/tableOfDataValues/addSummaryToTable.js
> +  return newResult;
```suggestion
const newColumns = [ ...tableData.columns, { key: summaryColumnKey, title }];
return { ...tableData, rows: newRows, columns: newColumns };
```

2020-12-21 23:11 UTC, billli0 commented
> I have the impression that the code as is will not calculate correct percentages for `RH Products Stock Availability (HFRSA and Spot Check Survey Data) With Percentage`

Thanks Kostas! You are one of those who loves to share every knowledge. I have a big lesson from your review. 
I can tell the 'percentage' is confusing, which actually is a funciton in `addSummaryToTable.js` instead of the one in `calculateOperationForAnalytics.js`. Because this is a customer 'percentage' for the row and column. Perhaps changing the function name can make it less confusing?

2020-12-21 23:22 UTC, kael89 commented
> Thanks Kostas! You are one of those who loves to share every knowledge. I have a big lesson from your review.
> I can tell the 'percentage' is confusing, which actually is a function in `addSummaryToTable.js` instead of the one in `calculateOperationForAnalytics.js`. Because this is a customer 'percentage' for the row and column. Perhaps changing the function name can make it less confusing?

I believe it's fine @billli0 , I could tell that the `percentage` used here was the one declared in `addSummaryToTable.js`. I believe the code will not be correct because of two main issues:

* https://github.com/beyondessential/tupaia/pull/1839#discussion_r546533352 - when data exist
* https://github.com/beyondessential/tupaia/pull/1839#discussion_r546509540 - when data are absent

In fact, I wanted to be sure so I run your code locally and for FIJI, I'm getting `NaN%` for all row summaries in 2020, and `0%` for all row summaries in 2019.

2020-12-21 23:29 UTC, billli0 commented
Sorry, I miss your comments. GitHub just hides some of those for me...

2020-12-22 04:52 UTC, billli0 commented on packages/web-config-server/src/apiV1/dataBuilders/generic/table/tableOfDataValues/tableOfCalculatedValuesForOrgUnits.js
> +    const columns = await this.buildColumns();
Thanks for your help Kostas, now I keep the chain as: 
`DataBuilder => TableOfDataValuesBuilder => TableOfCalculatedValuesBuilder`

Template design pattern is a great idea, but would like your opinion on this alternative design:

>     //buildValuesByCell() will be overided to assign value to 'this.columns'
>     this.valuesByCell = await this.buildValuesByCell(); 
>     ...
>     const columns = this.columns || (await this.buildColumns());

2020-12-23 06:50 UTC, kael89 requested changes
Looks great now @billli0 ! I prefer the pattern in your current implementation. A few changes here and there and this should be ready!

2020-12-23 06:50 UTC, kael89 commented on packages/web-config-server/src/apiV1/dataBuilders/generic/table/tableOfDataValues/helpers/addSummaryToTable.js
> +  if (valueSet.length === 0 || valueAllUndefined) return false;
(Detail) This check is slightly quicker: just one non `undefined` value is enough to do calculations

```suggestion
  const isAnyValueDefined = valueSet.some(value => value !== undefined);
  if (valueSet.length === 0 || !isAnyValueDefined) return false;
```

2020-12-24 00:40 UTC, billli0 commented
Thanks Kostas, I've moved `ORG_UNIT_COLUMNS_KEYS_SET` to `constant.js` to reuse it, and implemented your suggestion.

2020-12-24 04:36 UTC, kael89 approved these changes
Ready to go!

2021-02-24 00:39 UTC, kael89 approved these changes

2021-02-26 05:28 UTC, kael89 approved these changes

2021-03-02 03:44 UTC, merged