update ios release section of readme
beyondessential/tupaia pull request #1917
Opened 2021-01-19 20:28 UTC by tcaiger

### Issue #: Update meditrak readme with more instructions

2021-01-20 20:08 UTC, edmofro requested changes
Hey I just checked LastPass and the .zip only has the second provisioning profile in it? Probably LastPass being bad at handling attachments...could you try again?

2021-01-20 20:08 UTC, edmofro commented on packages/meditrak-app/README.md
> +  - When prompted to select a profile, select second profile called Tupaia_Distribution_Profile_2020__2021.mobileprovision
```suggestion
  - When prompted to select a profile, select second profile called Tupaia_MediTrak_Distribution_Profile_2020__2021.mobileprovision
```

2021-01-21 03:11 UTC, tcaiger commented
> Hey I just checked LastPass and the .zip only has the second provisioning profile in it? Probably LastPass being bad at handling attachments...could you try again?

I've re-uploaded and it seems to have saved properly now.

2021-01-21 03:12 UTC, edmofro approved these changes

2021-01-21 03:24 UTC, merged