1403 add strive molecular data overlays
beyondessential/tupaia pull request #2016
Opened 2021-02-05 04:34 UTC by avaek

Addresses: https://github.com/beyondessential/tupaia-backlog/issues/1403

2021-02-05 04:57 UTC, Alastair-L requested changes
Looks good! Just a few style notes which you can take or leave, and making the id meaningful.

2021-02-05 04:57 UTC, Alastair-L commented on packages/database/src/migrations/20210205033535-AddSTRIVEMolecularDataOverlays-modifies-data.js
> +  id: generateId(),
Generally the map overlays have more expressive ids than this. Your last one was good (`PG_STRIVE_K13_C580Y_Positive`)

2021-02-05 04:57 UTC, Alastair-L commented on packages/database/src/migrations/20210205033535-AddSTRIVEMolecularDataOverlays-modifies-data.js
> +const STR_QMAL05_OVERLAY = {
a) I like the way that you've reduced code duplication with BASE_OVERLAY

b) I know it's nitpicky, so feel free to ignore me here, but there's still a bit of duplication that could be removed here. A pattern that could work here (or next time) is 
```javascript
OVERLAYS_TO_IMPORT = [
   {
      id: 'something',
      dataElementCode: 'abc',
      name: 'boo!',
      programCode: 'hi',
   },
   //...
]
```
And then in the up migration:
```javascript
OVERLAYS_TO_INSERT.forEach(
({ id, name, dataElementCode, programCode }) => {
    overlay = {
      ...BASE_OVERLAY,
      id,
      name,
      measureBuilderConfig: {
        dataValues: {
          [dataElementCode]: 1,
        },
        programCode,
        entityAggregation: {
          aggregationType: 'REPLACE_ORG_UNIT_WITH_ORG_GROUP',
          dataSourceEntityType: 'village',
          aggregationEntityType: 'facility',
        },
      };
    // Import etc
});
```

Just a thought

2021-02-05 04:57 UTC, Alastair-L commented on packages/database/src/migrations/20210205033535-AddSTRIVEMolecularDataOverlays-modifies-data.js
> +    db.runSql(`
Remember `insertObject` works on every table! 🎉

2021-02-05 04:57 UTC, Alastair-L commented on packages/database/src/migrations/20210205033535-AddSTRIVEMolecularDataOverlays-modifies-data.js
> +    const OVERLAY_ID_TO_DELETE = await db.runSql(`
This call can be removed with static ids 🎉

2021-02-09 01:24 UTC, avaek commented
Thanks for the great suggestions @Alastair-L - I believe I've implemented them correctly, let me know what you think

2021-02-09 01:38 UTC, Alastair-L approved these changes
Looks great! I love seeing all that red :)

2021-02-09 01:38 UTC, Alastair-L commented on packages/database/src/migrations/20210205033535-AddSTRIVEMolecularDataOverlays-modifies-data.js
> +    id: 'STR_QMAL05_POSITIVE',
This is very nitpicky, but the existing overlay in that group has id: `PG_STRIVE_K13_C580Y_Positive`. Did you have a particular reason to deviate from that pattern?

2021-02-09 02:16 UTC, avaek commented
> This is very nitpicky, but the existing overlay in that group has id: PG_STRIVE_K13_C580Y_Positive. Did you have a particular reason to deviate from that pattern?

Great point! The format I followed was just based on a random map overlay in the STRIVE project but it makes sense to copy the `id` format of the existing map overlays in that particular map overlay group. I've updated the migration accordingly

2021-02-09 02:18 UTC, Alastair-L commented
Already approved, but consider it double approved now :)

2021-02-23 03:31 UTC, merged