2235 add lesmis package
beyondessential/tupaia pull request #2144
Opened 2021-02-25 22:17 UTC by tcaiger

### Issue #: [2235](https://github.com/beyondessential/tupaia-backlog/issues/2235) Set up LESMIS backend package

### Changes:

- add lesmis backend package
- add login, logout and user routes

2021-03-02 04:23 UTC, edmofro requested changes
I realise this is a draft PR but as I'm familiar with the code I went ahead and did a full review. I'd suggest we just keep the one PR rather than split it - I can keep reviewing the changes from here.

It's looking great to me. Regarding your questions:
- I prefer something like `server-boilerplate` to `tupaia-server` (which I think people might confuse as an actual service, probably with the responsibilities meditrak-server currently has)
- I'm on the fence with all of the questions about how much to move! There are arguments either way, but
  - I marginally favour `MeditrakConnection` et al. living in the `lesmis-server` package at the moment - handy because e.g. LESMIS might want to get all `meditrak-server` responses as camel case where other services might not, etc. If we get more server implementations and they're all using really similar api connection layers, that might change, but that's where I'm at right now.
  - I think yes to Login and Logout routes being in it. Given that it holds `AuthConnection` and that all tupaia servers should authenticate in the same way, that makes sense to me.
  - `createApp` function instead of base classes... My gut reaction was initially "yes", but after reading through I can also see it making it hard if we have a specific need for some express middleware and it's hard to see where to put it. Let's stick with the base classes for now. Sometimes trying too hard not to repeat yourself leads to confusion later, and I have the feeling this could be one of those places.
- Types between parent and child classes: could you give more context here?

2021-03-02 04:23 UTC, edmofro commented on packages/lesmis-server/src/routes/Route.ts
> +      this.reportConnection = new ReportConnection(session);
I would keep just these in the lesmis-server `Route` class, and have the parent include `handle()` with a call to `this.setupConnections` (another abstract method that can be implemented at this level)

2021-03-05 00:18 UTC, tcaiger commented on packages/tupaia-server/src/Route.ts
> +    return this.getSession();
I went for making the whole class abstract as well

2021-03-05 01:19 UTC, tcaiger commented on packages/tupaia-server/src/Route.ts
> +    return this.getSession();
Actually then I decided not to 😬

2021-03-07 19:53 UTC, tcaiger commented
@edmofro - this is ready for another review. Happy to discuss if it's easier when we are in the office. Regarding the types, I managed to answer my own question, so don't worry about that.

2021-03-07 20:27 UTC, edmofro approved these changes
Looks great! Went commit by commit, and definitely agree the with the call to return `LoginRoute` to extending `UnauthenticatedRoute` and using a different name for the verification step 👌 

Just a couple typos, but fully approved 🎉

2021-03-07 20:27 UTC, edmofro commented on packages/server-boilerplate/README.md
> +- When adding the routes to the app, you will need to wrap the routes with the the `handleRoute` util for the routes to work properly.
```suggestion
- When adding the routes to the app, you will need to wrap the routes with the `handleWith` util for the routes to work properly.
```

2021-03-07 20:27 UTC, edmofro commented on packages/server-boilerplate/README.md
> +- You also need to add the error hanlder as the fallback route.
```suggestion
- You also need to add the error handler as the fallback route.
```

2021-03-07 20:27 UTC, edmofro commented on packages/server-boilerplate/README.md
> +- Includes Route which is base class with useful functionality for handling responses. Route is an abstract class which must be extended to custom routes.
```suggestion
- Includes `Route` which is base class with useful functionality for handling responses. `Route` is an abstract class which must be extended to custom routes.
```

2021-03-09 19:52 UTC, merged