2485 fix duplicate y axis values
beyondessential/tupaia pull request #2274
Opened 2021-03-23 02:20 UTC by avaek

Addresses: https://github.com/beyondessential/tupaia-backlog/issues/2485

It seems that when the `valueType` for a report is `number` that it can cause a bug with the Y Axis if the values are less than 5 (shown below, the value there is 1 and the Y Axis is displaying "duplicate" values)
- I think what is happening is each tick in the Y Axis is really a decimal however they're being rounded up/down to whole numbers because of the number type (so it seems like duplicate values but really it's just the distinct decimals are being rounded up/down)
- Note: this report only has `"valueType": "number"` because I changed it to this for testing purposes locally, normally it does not

<img width="773" alt="Screen Shot 2021-03-23 at 3 07 55 PM" src="https://user-images.githubusercontent.com/25729153/112082587-c093ae00-8bd9-11eb-93ba-926335d0f604.png">

A solution I've found to this is just not allowing decimals when the `valueType` is `number`
- This solution changes the above report to look like this:

<img width="783" alt="Screen Shot 2021-03-23 at 3 09 31 PM" src="https://user-images.githubusercontent.com/25729153/112082849-27b16280-8bda-11eb-90c1-104d765e2e14.png">

2021-03-23 02:29 UTC, edmofro commented
Did you look in to allowing the decimals to show with a higher rounding precision if ticks have less than 1 full number's interval between them? I think that could be a nicer solution if it were possible

2021-03-23 02:31 UTC, avaek commented
> Did you look in to allowing the decimals to show with a higher rounding precision if ticks have less than 1 full number's interval between them? I think that could be a nicer solution if it were possible

I didn't but I can

2021-03-23 02:57 UTC, kael89 requested changes
I agree with [Edwin's comment](https://github.com/beyondessential/tupaia/pull/2274#issuecomment-804535755) that ideally we should allow decimals ticks. If eg our values are 0.02, 0.04, forcing integer ticks would make chart bars unnecessarily small. 

My suggestions are for the existing implementation, in case tey are relevant to the final implementation

2021-03-23 02:57 UTC, kael89 commented on packages/ui-components/src/components/Chart/YAxes.js
> +      allowDecimals={displayDecimals(valueType)}
```suggestion
      allowDecimals={valueType !== NUMBER}
```

(`NUMBER` can be exported from the `VALUE_TYPES` "enum" in line 12

We can then delete `displayDecimals`. Similarly for `CartesianChart`

2021-03-23 22:05 UTC, avaek commented
> Did you look in to allowing the decimals to show with a higher rounding precision if ticks have less than 1 full number's interval between them? I think that could be a nicer solution if it were possible

There are only 16 reports on Tupaia that explicitly have a `number` `valueType` - most reports that display numbers have an `undefined` `valueType` (and therefore use the default formatter, which displays numbers at 2 decimal places where relevant (meaning that they aren't affected by the bug that this PR fixes))
- The easiest solution seems to be to just force the reports that explicitly have a `number` `valueType` to also use the default formatter
- I briefly tested this locally and couldn't find anywhere where this change caused any display issues (although further testing by the testers is required)

This change means the example report I showed in the initial description on this PR now looks like this:

<img width="761" alt="Screen Shot 2021-03-24 at 10 51 08 AM" src="https://user-images.githubusercontent.com/25729153/112224597-972d5d80-8c7f-11eb-8c06-c576f2f1029b.png">

2021-03-25 02:34 UTC, kael89 approved these changes
Nice solution @avaek !

2021-04-12 23:56 UTC, merged