vaccine dose taken by day
beyondessential/tupaia pull request #2299
Opened 2021-03-26 00:59 UTC by billli0

### Issue #:
[Number of people received 1st dose of COVID-19 vaccine by day #2559](https://github.com/beyondessential/tupaia-backlog/issues/2559)
[Number of people received 2nd dose of COVID-19 vaccine by day#2560
](https://github.com/beyondessential/tupaia-backlog/issues/2560)
### Changes:

2021-03-26 03:16 UTC, chris-bes requested changes

2021-03-26 03:16 UTC, chris-bes commented on packages/database/src/migrations/20210325030144-VaccineDoseTakenByDayVaccineTracking-modifies-data.js
> +  for (const { code: dashboardGroupCode, hierarchyLevel } of dashboardGroups) {
Hmmm would this migration work? It doesn't seem to have `hierarchyLevel` in a dashboard group object?

2021-03-26 03:16 UTC, chris-bes commented on packages/database/src/migrations/20210325030144-VaccineDoseTakenByDayVaccineTracking-modifies-data.js
> +      const report = generateReport(dashboardGroupCode, hierarchyLevel, doseName, dataElementCode);
`generateReport()` also receives `aggregationEntityType`, but it seems like it's never passed in from here or anywhere else?

2021-03-26 12:02 UTC, chris-bes commented
@billli0 I fixed up the migration so maybe you can re-review it?

2021-03-28 22:43 UTC, billli0 commented
LGTM

2021-03-28 22:44 UTC, chris-bes approved these changes

2021-03-28 22:45 UTC, merged