2502 lesmis map overlays
beyondessential/tupaia pull request #2391
Opened 2021-04-14 21:52 UTC by tcaiger

### Issue #: [2502](https://github.com/beyondessential/tupaia-backlog/issues/2502) LESMIS Map Overlays

### Changes:

- Example

---

2021-04-15 04:10 UTC, tcaiger commented on packages/ui-components/src/components/Map/Legend/Legend.js
adding support for hidden measures and formatting

2021-04-15 04:11 UTC, tcaiger commented on packages/ui-components/src/components/Map/Legend/LegendEntry.js
> +  ({ marker, label, value, onClick, hiddenMeasures, unClickable }) => {
add support for hidden measures

2021-04-15 04:11 UTC, tcaiger commented on packages/ui-components/src/components/Map/Legend/MarkerLegend.js
> +  ({
add support for hidden measures

2021-04-15 04:12 UTC, tcaiger commented on packages/ui-components/src/components/Map/Legend/MarkerLegend.js
> -import { FlexStart } from '../../Layout';
remove this reference to layout because it's outside the `Map` module

2021-04-15 04:12 UTC, tcaiger commented on packages/ui-components/src/components/Map/Legend/SpectrumLegend.js
> +
remove this reference to layout because it's outside of the 'map' module

2021-04-15 04:13 UTC, tcaiger commented on packages/ui-components/src/components/Map/MarkerLayer.js
> +const ShadedPolygon = styled(Polygon)`
add support for polygon overlays

2021-04-15 23:01 UTC, edmofro commented on packages/ui-components/src/components/Map/MapContainer.js
> +  bounds,
Great change

2021-04-15 23:05 UTC, edmofro commented on packages/ui-components/src/components/Map/Polygon.js
> +export const Polygon = ({ entity }) => {
Nice rename

2021-04-15 23:07 UTC, edmofro commented on packages/ui-components/src/components/Map/PolygonLayer.js
> +    ?.filter(e => Array.isArray(e.region))
Shouldn't need the `?` here as you've got the early return

2021-04-15 23:48 UTC, edmofro requested changes
As discussed, just the `hiddenMeasures` rename

2021-04-16 01:51 UTC, edmofro approved these changes

2021-04-20 03:53 UTC, merged