2606 add unknown entities to Samoa and exclude from explore
beyondessential/tupaia pull request #2460
Opened 2021-04-23 04:45 UTC by avaek

Addresses: https://github.com/beyondessential/tupaia-backlog/issues/2606

Basically this migration creates "Unknown" entities for Samoa for the `district`, `facility` and `village` types (e.g. "Unknown District", "Unknown Village" etc) and excludes them from showing up in the Explore project by strictly defining which districts should be visible in Explore in the `entity_relation` table (e.g. only the two existing districts & not the new "Unknown" one)

2021-04-26 21:43 UTC, edmofro commented on packages/database/src/migrations/20210422030246-CreateUnknownEntitiesForSamoa-modifies-data.js
> +  parent_id: '5df1b88c61f76a485cd1ca09',
I think I've said this in an earlier PR review for you - please don't just have ids with no explanation.

Ideal way: Add an extra query that fetches the id based on the entity code

Not so ideal way: Hard code the id with a comment indicating the code it relates to

Not allowed way: Just the id

Would be great to do this in the ideal way - search `codeToId` in `migrations` for examples

![Screen Shot 2021-04-27 at 9 43 15 AM](https://user-images.githubusercontent.com/1274422/116154660-0f82b500-a73d-11eb-989c-df712acebc28.png)

2021-04-26 21:44 UTC, edmofro requested changes
Clever solution! Just a minor point to fix up to make it more readable and robust

2021-04-28 00:43 UTC, avaek commented
Thanks for the review @edmofro - makes perfect sense! I've made those changes, they can perhaps be done in a cleaner way but this way works & I felt like I was wasting too much time trying to figure out how to do it more cleanly

2021-04-28 00:52 UTC, edmofro requested changes
Yeah the more DRY way to do this would be to pull out a util function called `nameToId` which just contains the code you've repeated in the up and down. But this is all good - please just change the case on those variable names

2021-04-28 00:52 UTC, edmofro commented on packages/database/src/migrations/20210422030246-CreateUnknownEntitiesForSamoa-modifies-data.js
> +  const SELECT_EXPLORE_ENTITY_HIERARCHY = await db.runSql(`
consts inside the function generally use camelCase rather than UPPER_SNAKE_CASE

2021-04-28 00:52 UTC, edmofro commented on packages/database/src/migrations/20210422030246-CreateUnknownEntitiesForSamoa-modifies-data.js
> +  const [EXPLORE_ENTITY_HIERARCHY] = SELECT_EXPLORE_ENTITY_HIERARCHY.rows;
Clever destructuring of the first array item!!

2021-04-28 01:44 UTC, avaek commented
> Yeah the more DRY way to do this would be to pull out a util function called nameToId which just contains the code you've repeated in the up and down. But this is all good - please just change the case on those variable names

Ohh yup that makes sense, thanks! I've fixed up the variable names now

2021-04-28 01:51 UTC, edmofro approved these changes
Nice work @avaek!

2021-05-09 23:41 UTC, merged