Add country level trend graph, overlaid years
beyondessential/tupaia pull request #2503
Opened 2021-05-04 05:45 UTC by PShoe

### Issue  [1750](http://github.com/beyondessential/tupaia-backlog/issues/1750)

### Changes:

- add new data builder 

Notes:
- should refactor parseChartConfig.js ```setOpacityValues(
    addDefaultColorsToConfig(sortChartConfigByLegendOrder(baseConfig), paletteName, chartType),
  );``` to use call backs

- Example

---

### Screenshots:

2021-05-04 05:53 UTC, PShoe commented on packages/database/src/migrations/20210504040112-AddPsssCountryTrendDashboardsPastYears-modifies-data.js
> +exports.down = async function (db) {
@reviewer - guessing there's a better way than nested for loops?

2021-05-04 05:54 UTC, PShoe commented on packages/web-config-server/src/apiV1/utils/layerYearOnYear.test.js
> +/**
@reviewer - I feel like this test may be in the wrong location?

2021-05-04 05:55 UTC, PShoe commented on packages/web-frontend/src/components/View/ChartWrapper/parseChartConfig.js
> +    addDefaultColorsToConfig(sortChartConfigByLegendOrder(baseConfig), paletteName, chartType),
@reviewer - this can be refactored using callbacks

2021-05-04 06:05 UTC, PShoe commented on packages/web-config-server/src/apiV1/dataBuilders/generic/analytics/analyticsYearOnYear.js
> +    this.query.endDate = this.getTodayDataEndDate().format('YYYY-MM-DD');
@reviewer - I feel weird about how I named this.getTodayDataEndDate

2021-05-04 06:27 UTC, IgorNadj commented on packages/aggregator/src/analytics/aggregateAnalytics/aggregateAnalytics.js
> +    case AGGREGATION_TYPES.YEAR_ON_YEAR:
Pretty sure this was and old attempt, we did it all in web-config-server in the end right?

2021-05-04 06:38 UTC, rohan-bes requested changes
Sorry @PShoe I have to finish early today but I'll continue this review later tonight/thursday

2021-05-04 06:38 UTC, rohan-bes commented on packages/aggregator/src/analytics/aggregateAnalytics/aggregations/index.js
> +export { layerYearOnYear } from './layerYearOnYear';
I'm quite confused... this file doesn't exist? Is it meant to be imported from `utils`?

2021-05-06 01:03 UTC, rohan-bes requested changes
Part way through, will continue later today

2021-05-11 02:24 UTC, rohan-bes commented on packages/web-config-server/src/apiV1/dataBuilders/generic/analytics/analyticsYearOnYear.js
> +    this.query.startDate = this.getDataStartDate().format('YYYY-MM-DD');
I ran the zoom functionality by @tcaiger and he seemed to be a fan of it and was happy for us to introduce it as a general feature across charts 🎉  I've created a card for it: https://github.com/beyondessential/tupaia-backlog/issues/2785

We don't necessarily need to implement it as part of this ticket, however when it does get implemented, there may need to be a couple of changes to this code:
1. No need to adjust the start/end dates of the query here
2. Revert changes to the date picker logic that have been implemented as part of this PR

2021-05-14 03:07 UTC, rohan-bes requested changes
Just a few minor changes requested. But definitely look at the import issue as it's failing your tests 👍 

Aside from that all looking good 🎉

2021-05-14 03:07 UTC, rohan-bes commented on packages/web-config-server/src/apiV1/dataBuilders/generic/analytics/analyticsYearOnYear.js
> +      analytic = analytic.format('YYYY-MM-DD');
```suggestion
      const formattedAnalyticPeriod = periodToMoment(layeredAnalytic.period).format('YYYY-MM-DD');
```
Always nice to give variables a clear name representing what they are 👍

2021-05-14 03:07 UTC, rohan-bes commented on packages/web-config-server/src/apiV1/dataBuilders/generic/analytics/analyticsYearOnYear.js
> +    let series = [];
```suggestion
    const series = [];
```

2021-05-14 03:07 UTC, rohan-bes commented on packages/web-config-server/src/apiV1/dataBuilders/generic/analytics/analyticsYearOnYear.js
> +      let yearsAgo = this.getDataEndDate().year() - year;
```suggestion
      const yearsAgo = this.getDataEndDate().year() - year;
```

2021-05-19 00:07 UTC, PShoe commented on packages/web-config-server/src/tests/apiV1/utils/layerYearOnYear.test.js
> +import { layerYearOnYear } from '../../../../apiV1/utils/layerYearOnYear';
fixed `import { layerYearOnYear } from '../../../apiV1/utils/layerYearOnYear';`

2021-05-21 05:01 UTC, rohan-bes approved these changes
Great work @PShoe!

2021-05-21 07:25 UTC, merged

2021-05-21 07:25 UTC, PShoe commented
Going to merge into epic branch for QA testing on epic.