fetchEvents() to handle multiple data groups in report server
beyondessential/tupaia pull request #2628
Opened 2021-06-02 04:29 UTC by billli0

### Issue #:
no issue

### Changes:
we want to fetch multiple dataGroups in report-server, ultimately we would want Aggregator to handle that.

2021-06-02 04:47 UTC, billli0 commented on packages/report-server/src/reportBuilder/fetch/functions/dataGroup.ts
> +    results: results.flat(),
I tried to use .flatMap() but it seems like TypeScript having trouble mapping the types here and throwing a type error.

2021-06-02 23:45 UTC, rohan-bes requested changes
Looks great @billli0! Can't wait to use this

One request though, I believe we also need to update the validator for `validateDataGroups()` to allow for more than 1 `dataGroup`?

2021-06-02 23:45 UTC, rohan-bes commented on packages/report-server/src/reportBuilder/fetch/functions/dataGroup.ts
> +  // TODO: Eventually we want Aggregator to handle fetching multiple dataGroups
Appreciate this comment so that we know the plan for the future! 🎉

2021-06-03 01:54 UTC, billli0 commented
> Looks great @billli0! Can't wait to use this
> 
> One request though, I believe we also need to update the validator for `validateDataGroups()` to allow for more than 1 `dataGroup`?

Thanks @rohan-bes , good catching!

2021-06-03 02:06 UTC, rohan-bes approved these changes
Awesome!

2021-06-04 01:03 UTC, billli0 commented
Note that if we fetch with `{dataGroups: ['A', 'B'], dataElements: ['A_1', 'A_2', 'B_1', 'B_2'] }`, it will send all the dataElements grouping with each dataGroup, like `{dataGroupCode: ['A'], dataElements: ['A_1', 'A_2', 'B_1', 'B_2']}`, instead of doing it with filtered dataElements like `{dataGroupCode: ['A'], dataElements: ['A_1', 'A_2']`. 

But Aggregator is smart enough to filter them itself, which is very handy. 👍

2021-06-04 01:04 UTC, merged