2928 refactor lesmis dashboard view 2
beyondessential/tupaia pull request #2748
Opened 2021-06-29 02:56 UTC by tcaiger

### Issue #:

### Changes:

- Example

---

### Screenshots:

2021-06-29 03:09 UTC, tcaiger commented on packages/lesmis/src/api/queries/useVitalsData.js
> +    data: {
add api data to the data key to keep the react-query convention

2021-06-29 03:10 UTC, tcaiger commented on packages/lesmis/src/components/EntityVitalsItem.js
> +const VitalName = styled(Typography)`
update styles to match design

2021-06-29 03:11 UTC, tcaiger commented on packages/lesmis/src/views/DashboardReportTabView.js
> +                key={dashboard.dashboardId}
update to use a unique key

2021-06-29 03:15 UTC, tcaiger commented on packages/lesmis/src/views/DashboardView.js
> +                    isLoading={!!isFetching}
Set up loading state on year selector. This will be used in the next PR.

2021-06-29 03:25 UTC, tcaiger commented on packages/lesmis/src/views/VitalsViews.js
> +        value={vitals.Population?.toLocaleString()}
Add commas to numbered fields

2021-06-30 04:30 UTC, edmofro requested changes
Somewhat inclined to split up the vitals file further into:
- partners section
- each entity type vital
- the loader + vitals outer component

But totally up to you. Only required changes are a couple of very small ones inline

2021-06-30 04:30 UTC, edmofro commented on packages/lesmis/src/views/VitalsViews.js
> +      <EntityVitalsItem name="Complete School" icon="Notepad" isLoading={vitals.isLoading} />
```suggestion
      <EntityVitalsItem name="Complete School" icon="Notepad" />
```

2021-06-30 04:30 UTC, edmofro commented on packages/lesmis/src/views/DashboardView.js
> +    useYearSelector: true,
```suggestion
```

2021-06-30 04:30 UTC, edmofro commented on packages/lesmis/src/views/VitalsViews.js
> +const PartnersSection = ({ vitals, displayAll }) => {
I reckon this PartnersSection could be split out again

2021-06-30 23:01 UTC, tcaiger commented
@edmofro - I have added the small inline changes and done a bit more refactoring based on your nudging to split up the file further and based on always showing the partners section. Here is a summary:

- move the data processing for the partners logos into `useEntityVitals` and moved partners section template inline
- moved the map/photo components inline
- - extracted out the Vitals loader into a new file
- renamed VitalsViews to VitalsView

I decided to keep the Vitals entity templates in the same file as they are super specific to the VitalsView and use the vitals props which could be confusing out of context.

2021-07-01 01:36 UTC, edmofro commented on packages/lesmis/src/api/queries/useVitalsData.js
> +    data: { ...vitalsData, partners },
Great idea to move the data to here!!

2021-07-01 01:37 UTC, edmofro approved these changes
Yep all looks good :-)

2021-07-04 22:09 UTC, merged