3173 move mobile entity navigation
beyondessential/tupaia pull request #2822
Opened 2021-07-13 02:34 UTC by tcaiger

### Issue #:

### Changes:

- Example

---

### Screenshots:

2021-07-14 22:28 UTC, edmofro commented on packages/web-frontend/src/containers/mobile/EntityNav.js
> +          <NoResultsText>No clinics found in this region.</NoResultsText>
```suggestion
          <NoResultsText>No children found within the current entity.</NoResultsText>
```

2021-07-14 22:35 UTC, edmofro requested changes
Have made some suggestions, but overall I also think the UX here also needs some work, because it would be unclear to the user how to select the entity and see their dashboards vs. just drill down to find the entity they're looking for. 

Would be great if we could separate out those two actions. 

It would also be really nice if we could make the existing SearchBar on Tupaia.org responsive and use that here, though I realise that sounds like potentially a lot more work for a quick win

2021-07-14 22:35 UTC, edmofro commented on packages/web-frontend/src/containers/mobile/EntityNav.js
> +
```suggestion
```

2021-07-14 22:35 UTC, edmofro commented on packages/web-frontend/src/containers/mobile/EntityNav.js
> +    title,
```suggestion
```

2021-07-14 22:35 UTC, edmofro commented on packages/web-frontend/src/containers/mobile/EntityNav.js
> +  title,
```suggestion
```

2021-07-14 22:35 UTC, edmofro commented on packages/web-frontend/src/containers/mobile/EntityNav.js
> +  title: PropTypes.string,
```suggestion
```

2021-07-14 22:35 UTC, edmofro commented on packages/web-frontend/src/containers/mobile/EntityNav.js
> +  title: '',
```suggestion
```

2021-07-14 22:35 UTC, edmofro commented on packages/web-frontend/src/containers/mobile/EntityNav.js
> +          title={title}
```suggestion
          title="Browse Entities"
```

2021-07-14 22:35 UTC, edmofro commented on packages/web-frontend/src/containers/mobile/EntityNav.js
> +const EntitySearchComponent = ({
```suggestion
const EntityBrowseComponent = ({
```

2021-07-14 22:35 UTC, edmofro commented on packages/web-frontend/src/containers/mobile/EntityNav.js
> +EntitySearchComponent.propTypes = {
```suggestion
EntityBrowseComponent.propTypes = {
```

2021-07-14 22:35 UTC, edmofro commented on packages/web-frontend/src/containers/mobile/EntityNav.js
> +EntitySearchComponent.defaultProps = {
```suggestion
EntityBrowseComponent.defaultProps = {
```

2021-07-14 22:35 UTC, edmofro commented on packages/web-frontend/src/containers/mobile/EntityNav.js
> +)(EntitySearchComponent);
```suggestion
)(EntityBrowseComponent);
```

2021-07-30 03:32 UTC, tcaiger commented
Closing as needs design work

2021-07-30 03:32 UTC, closed without merging