WAI-41 Average Cohort Survival
beyondessential/tupaia pull request #3188
Opened 2021-09-09 02:18 UTC by EMcQ-BES

### Issue #:
Resolves WAI-41

### Changes:

- Add an attribute type to non-target districts
- Add a new HLO1 list visual for primary education at country level
- Add indicators to calculate average vs target cohort survival rate
- Add a drilldown graph

---

### Screenshots:
See attached ticket

2021-09-09 21:15 UTC, edmofro requested changes
Before I review the indicators etc., could you please update the report to use the [new config](https://beyond-essential.slab.com/posts/report-server-transform-config-design-change-proposals-k8l3tch0) that just got merged to dev? Cheers!

2021-09-09 22:18 UTC, EMcQ-BES commented on packages/database/src/migrations/20210907222655-LESMISPrimaryEducationCohortSurvivalRate-modifies-data.js
> +      dashboardCode: 'LESMIS_ESSDP_PrimarySubSector_HLO1',
Just realised that I only actually added this dashboard in WAI-44 so while it was working on my local it actually relies on [another PR](https://github.com/beyondessential/tupaia/pull/3171)

I'm just going to wait until that PR gets merged so I don't have to do complicated git stuff

2021-09-09 23:13 UTC, edmofro commented on packages/database/src/migrations/20210907222655-LESMISPrimaryEducationCohortSurvivalRate-modifies-data.js
> +        // 1 year is defined separately because I don't want to handle singular/plural year(s)
And fair enough too

2021-09-09 23:16 UTC, edmofro commented on packages/database/src/migrations/20210907222655-LESMISPrimaryEducationCohortSurvivalRate-modifies-data.js
> +      using: 'last',
```suggestion
```
Default is now `single`, which adds the extra assertion that we are only expecting one to be defined

2021-09-09 23:18 UTC, edmofro commented on packages/database/src/migrations/20210907222655-LESMISPrimaryEducationCohortSurvivalRate-modifies-data.js
> +      using: 'last',
Same deal

2021-09-09 23:19 UTC, edmofro approved these changes
Couple of suggestions but lgtm!

2021-09-10 00:15 UTC, edmofro approved these changes

2021-09-19 21:13 UTC, merged