RN-188 Enabling and disabling of selected options
beyondessential/tupaia pull request #3670
Opened 2022-02-09 04:55 UTC by billli0

### Issue #:
RN-188

### Screenshots:
https://linear.app/bes/issue/RN-188#comment-3dedc555

2022-02-09 04:58 UTC, billli0 commented on packages/admin-panel/src/VizBuilderApp/context/VizConfig.js
> +      }}
Provide a new context `VisualisationContext`, which works like a selector but no caching ability.

2022-02-11 04:23 UTC, rohan-bes requested changes
Looks great @billli0 this is such awesome functionality!

Couple of minor renames, and a bit of a refactor request, lemme know what you think 👍

2022-02-15 00:55 UTC, billli0 commented on packages/admin-panel/src/VizBuilderApp/components/DataLibrary/AggregationDataLibrary.js
> +        <ColHeader>
My original thought is to make thing clearer than passing a prop. One of the benefits is we can avoid to pass `onChangeForCheckbox` or `checkboxConfig` for all `setState()` hooks, which makes code more readable and straigtfoward. 

It seems to bring more confusion than readability. I'm happy to pass prop `supportsDisableAll` to enable the checkbox.

2022-02-15 00:56 UTC, billli0 commented on packages/admin-panel/src/VizBuilderApp/components/DataLibrary/AggregationDataLibrary.js
> +              });
Yeah, will change it to `baseValue` to make more sense.

2022-02-18 05:21 UTC, rohan-bes approved these changes
Nice work @billli0 super useful!

2022-02-18 05:33 UTC, merged