Remove tests from dist
beyondessential/tupaia pull request #4029
Opened 2022-07-14 05:25 UTC by IgorNadj

Followup fixes to yarn v1 -> v3 upgrade #3994

2022-07-15 00:48 UTC, billli0 requested changes
LGTM! Seems like there is a testing error in `web-config-server` from codeship, wanna have a quick fix?

2022-07-15 05:05 UTC, IgorNadj commented on packages/meditrak-app/.yarnrc.yml
> +nmHoistingLimits: workspaces
Fixes an issue Andrew found with building meditrak-app locally. 
<img width="892" alt="Screen Shot 2022-07-15 at 1 23 06 PM" src="https://user-images.githubusercontent.com/667652/179154078-86334df9-c063-46fe-8e6c-ae1d0c2847a5.png">

yarn v3 doesn't support nohoist, but instead we have to say don't hoist anything.

2022-07-15 05:05 UTC, IgorNadj commented on packages/server-boilerplate/src/index.ts
> +export { TestableServer } from './testUtilities';
Moved testUtilities out of `__tests__` because `__tests__` doesn't get ouput into dist, and other packages need these testUtilities.

2022-07-15 05:05 UTC, IgorNadj commented on packages/tsutils/package.json
> +    "build": "rm -rf dist && npm run --prefix ../../ package:build:ts",
Use standard ts build script

2022-07-15 05:05 UTC, IgorNadj commented on packages/ui-components/src/__tests__/components/Chart/parseChartConfig.test.js
> +import { parseChartConfig } from '../../../components/Chart/parseChartConfig';
Update ui-components folder structure to put all tests under `__tests__` instead of alongside each component for consistency with all other packages.

2022-07-15 05:05 UTC, IgorNadj commented on packages/weather-api/package.json
> +    "test": "yarn package:test",
Use standard test runner

2022-07-15 06:12 UTC, IgorNadj commented
@billli0 Went to far in my original changes, had to roll back some packages. I was hoping we could get our old packages like web-config-server to use the normal build and test configs, but they have special needs so I rolled them back to use their old custom build and test scripts. Ready for re-review.

2022-07-18 01:34 UTC, billli0 commented on packages/central-server/package.json
> +    "build:src": "yarn package:build:js",
Can we ignore them to make the bundle file smaller?

2022-07-18 01:46 UTC, billli0 approved these changes
New changes look good, thanks for the fix. Definitely it would be nice to have `web-config-server` updated to be more standardised as other packages. 
You mentioned the `web-config-server` have its own needs, what would that be? Will it be a big one for us the refactor?

2022-07-18 04:47 UTC, IgorNadj commented
> New changes look good, thanks for the fix. Definitely it would be nice to have `web-config-server` updated to be more standardised as other packages. You mentioned the `web-config-server` have its own needs, what would that be? Will it be a big one for us the refactor?

There are still a few packages that use mocha. To get these to use the standard test runner (jest) we will need to go through all tests and migrate them, some of the syntax is different, like expect().to.be instead of expect().toBe or something like that. Not too big but I thought it is probably out of scope for this PR.

2022-07-18 05:03 UTC, IgorNadj commented on packages/central-server/package.json
> +    "build:src": "yarn package:build:js",
I came back to this with a fresh head and moved these flags to the .babelrc.js file. This way we can use the standard build script as well as customise the build babel config for central-server. 

We are now back to 9MB builds, 3MB smaller (same as dev), and as fast as dev.

2022-07-18 05:17 UTC, billli0 commented
> There are still a few packages that use mocha. To get these to use the standard test runner (jest) we will need to go through all tests and migrate them, some of the syntax is different, like expect().to.be instead of expect().toBe or something like that. Not too big but I thought it is probably out of scope for this PR.

Yeah I'm just a little bit curious. It is definitely out of scope. 
I was working on `web-config-server` unit test and I'm not really satisfied with `mocha`.. I have some interest to migrate that, will see how that goes.

2022-07-18 05:59 UTC, merged