MAUI-775: Custom report for Tonga Covid Raw Data
beyondessential/tupaia pull request #4171
Opened 2022-09-15 14:55 UTC by chris-pollard

### Issue MAUI-775:

### Changes:
- Add one report solely in javascript
- Add another report with same output but using a raw sql execution.

2022-09-15 14:56 UTC, chris-pollard commented
Note that there are two versions here; one is javascript only, the other uses .executeSql() to directly query the database using the existing sql code for the dagster report. I did this to compare performance, but turns out there's not a huge difference. javascript is approx 31-32 seconds, sql is 29 seconds. I'd like some advice here, as to how to manage this within the timeout period.

2022-09-16 00:08 UTC, rohan-bes requested changes
Looks pretty good @chris-pollard! Can't wait to have this one in! Happy to pair on the performance issues together, but my first recommendation would be to look for areas where async logic can be parallelised 👍

2022-09-16 05:56 UTC, chris-pollard commented on packages/report-server/src/reportBuilder/customReports/tongaCovidRawData.ts
> +const NOW = new Date();
Ah, no, I definitely didn't mean that.

2022-09-16 06:39 UTC, chris-pollard commented on packages/report-server/src/reportBuilder/customReports/tongaCovidRawData.ts
> +  const resultsEvents = await fetch(resultsOptions);
Yes, good idea. I implemented this, and it saves about 4 seconds.

2022-09-19 00:17 UTC, rohan-bes commented
Closing in favour of https://github.com/beyondessential/tupaia/pull/4176

2022-09-19 00:17 UTC, closed without merging