no-issue: Improve Admin Panel Password Security
beyondessential/tupaia pull request #4220
Opened 2022-10-14 10:55 UTC by chris-pollard

### No-Issue:

### Changes:

- Exclude password from state.
- Disable react Devtools in production

2022-10-16 23:22 UTC, rohan-bes requested changes
Thanks for this @chris-pollard! One request to clean up the associated actions/selectors/reducers for getting/setting the password.

Also wanted to double check, how does this component behave if a user changes the email address while there's something in the password box? I'd expect the password to disappear?

2022-10-16 23:22 UTC, rohan-bes commented on packages/admin-panel/src/index.js
> +}
No this is probably a good call, thanks @chris-pollard 👍

2022-10-16 23:22 UTC, rohan-bes commented on packages/admin-panel/src/authentication/LoginForm.js
> +    dispatch(login(stateProps.emailAddress, password));
Thanks for making this change. Hopefully we can steadily transition most of the app state out of redux and into it's relevant components 👍

2022-10-16 23:22 UTC, rohan-bes commented on packages/admin-panel/src/authentication/LoginForm.js
> +import { getEmailAddress, getErrorMessage, getIsLoading, getRememberMe } from './selectors';
Can also delete the `getPassword` selector itself?

2022-10-16 23:22 UTC, rohan-bes commented on packages/admin-panel/src/authentication/LoginForm.js
> +import { changeEmailAddress, login, changeRememberMe } from './actions';
Can also delete the `changePassword` action itself?

2022-10-17 13:04 UTC, chris-pollard commented
> Thanks for this @chris-pollard! One request to clean up the associated actions/selectors/reducers for getting/setting the password.
> 
> Also wanted to double check, how does this component behave if a user changes the email address while there's something in the password box? I'd expect the password to disappear?

@rohan-bes regarding email address change, I have had a look and a change in email address does not seem to affect the state or behaviour of the password input. I had a look at Facebook.com as an example, and it acts the same way. You can change the email address after writing password and the password will not be affected.

2022-12-04 23:00 UTC, IgorNadj approved these changes
Adding tick, already reviewed

2023-02-09 00:25 UTC, chris-pollard commented
@rohan-bes for some reason, it seems to still require your approval.

2023-02-21 00:56 UTC, chris-pollard commented
@rohan-bes this seems to still require your approval, even though Igor already did.

2023-02-21 01:11 UTC, rohan-bes approved these changes

2023-03-08 23:15 UTC, merged