Added startDate and endDate selectors to the viz-builder
beyondessential/tupaia pull request #4408
Opened 2023-03-28 04:15 UTC by rohan-bes

Needed to do this to test the changes in https://github.com/beyondessential/tupaia/pull/4406

Such a simple feature, and it makes the viz-building experience so much better. So I feel it's worth it

2023-03-29 00:20 UTC, biaoli0 requested changes
@rohan-bes Thanks for adding the date selector in viz builder! It will make everyone's life easier!

Just request a minor change to handle a special user case.

2023-03-29 00:20 UTC, biaoli0 commented on packages/admin-panel/src/VizBuilderApp/components/PreviewOptions.js
> +    if (!date) {
I suggest to set value when it is null. User case is user wants to see all data from all period, they will delete the previous date input.

2023-03-29 00:20 UTC, biaoli0 commented on packages/admin-panel/src/VizBuilderApp/components/PreviewOptions.js
> +    if (!date) {
same here

2023-04-03 04:37 UTC, rohan-bes commented on packages/admin-panel-server/src/routes/FetchReportPreviewDataRoute.ts
> +    endDate: string;
Ah I see, will make it optional I think 👍

2023-04-03 23:22 UTC, biaoli0 approved these changes
LGTM!

2023-04-03 23:28 UTC, merged