MAUI-101: Fix horizontal scrolling
beyondessential/tupaia pull request #4464
Opened 2023-04-17 04:59 UTC by tcaiger

### Issue #: MAUI-101: Fix horizontal scrolling

### Changes:

- Move scroll bar to top of table
- Make nav bar responsive

---

### Screenshots:

Before
![Screen Shot 2023-04-17 at 4 56 43 PM](https://user-images.githubusercontent.com/12807916/232382598-15e80745-baae-4b98-b5b7-49828355a799.png)

---

![Screen Shot 2023-04-17 at 4 56 54 PM](https://user-images.githubusercontent.com/12807916/232382609-ae99591c-3455-4ad4-a4a9-33d43d898b2e.png)

After

![Screen Shot 2023-04-17 at 4 52 15 PM](https://user-images.githubusercontent.com/12807916/232382624-b87564f4-7de9-4667-a632-578f104a185e.png)

---

![Screen Shot 2023-04-17 at 4 53 16 PM](https://user-images.githubusercontent.com/12807916/232382619-2dbb39b3-8e16-4d87-83d1-6f10a33ff251.png)

2023-04-18 01:42 UTC, acdunham commented
Looks good, however when I run it locally on my machine I'm getting prop types errors:
![image](https://user-images.githubusercontent.com/129009580/232647843-004b804e-1d82-415c-a85c-022b003a8e9f.png)

2023-04-18 01:43 UTC, acdunham requested changes
Looks good, just need to fix these prop types errors, and then should be good to go
![image](https://user-images.githubusercontent.com/129009580/232648021-ee113f8e-fa66-467b-955b-5b615cd4a0a2.png)

2023-04-21 01:59 UTC, tcaiger commented
> Looks good, just need to fix these prop types errors, and then should be good to go ![image](https://user-images.githubusercontent.com/129009580/232648021-ee113f8e-fa66-467b-955b-5b615cd4a0a2.png)

Thanks for that!

2023-04-24 02:37 UTC, acdunham approved these changes

2023-04-28 04:12 UTC, merged