MDEV-137: Edit project countries in the Admin Panel
beyondessential/tupaia pull request #4483
Opened 2023-04-21 02:14 UTC by tcaiger

### Issue #: MDEV-137: Edit project countries in the Admin Panel

### Changes:

- Example

---

### Screenshots:

2023-05-02 04:18 UTC, acdunham approved these changes
Looks fine to me! Nice tests.

2023-05-07 22:28 UTC, EMcQ-BES requested changes
At some point I wanna update our database model to handle through tables better so we don't have to write this much custom code to use them.

The logic itself looks pretty solid, but there's a few spots we might be able to clean-up the code structure

2023-05-07 22:28 UTC, EMcQ-BES commented on packages/central-server/src/apiV2/projects/EditProject.js
> +export class EditProject extends EditHandler {
Also just acknowledging that @acdunham wrote an `EditProject.js` file which is part of the landing pages epic atm, so this'll cause a pretty major conflict when we have to merge those

2023-05-07 22:28 UTC, EMcQ-BES commented on packages/central-server/src/apiV2/GETProjects.js
> +    const countriesById = await this.getProjectCountriesByProjectId();
Getting all countries for all projects when only requesting a single record seems excessive? Maybe we can split out a singular version of the `getProjectCountries` function

2023-05-07 22:28 UTC, EMcQ-BES commented on packages/central-server/src/apiV2/projects/EditProject.js
> +  async createProjectEntityRelations(models, projectId, countries) {
Again, might be worth breaking this out into the `modelClasses`

```
this.models.project.createProjectEntityRelations(this.recordId, countries);
```

2023-05-07 22:35 UTC, EMcQ-BES commented on packages/central-server/src/tests/apiV2/projects/EditProject.test.js
> +  before(async () => {
Codeship complaining about this `before` 🤔

2023-05-09 01:28 UTC, tcaiger commented on packages/central-server/src/apiV2/projects/EditProject.js
> +export class EditProject extends EditHandler {
Inheritance for the win

2023-12-11 02:24 UTC, closed without merging