WAITP-1431: Update url with country code
beyondessential/tupaia pull request #5182
Opened 2023-11-16 03:11 UTC by tcaiger

### Issue #: WAITP-1431: Update url with country code

### Changes:

- Example

---

### Screenshots:

2023-11-17 00:19 UTC, acdunham requested changes
This is looking really good! Just noticed that the recent surveys and recent responses tiles don't direct to have the country in the URL though, which causes an error. 

I guess it might also open up the question - should project code be in the URL as well? I had a scenario, for example, where I went directly to a survey URL for a survey in Tonga, but my previously selected project was STRIVE, which meant I got an error fetching entities because STRIVE project doesn't have Tonga as a country. So we would get similar issues to what we had before the country was in the URL. What do you think?

2023-11-17 01:04 UTC, tcaiger commented
> This is looking really good! Just noticed that the recent surveys and recent responses tiles don't direct to have the country in the URL though, which causes an error.
> 
> I guess it might also open up the question - should project code be in the URL as well? I had a scenario, for example, where I went directly to a survey URL for a survey in Tonga, but my previously selected project was STRIVE, which meant I got an error fetching entities because STRIVE project doesn't have Tonga as a country. So we would get similar issues to what we had before the country was in the URL. What do you think?

Oh yes good questions. Here's a summary from our chat.

- Don’t need project code in the url as we can use survey.project_id
- Auto update user preferred country and project on deep linking
- Add toasts whenever user preferences are changed

2023-11-17 22:21 UTC, tcaiger commented on packages/datatrak-web-server/src/routes/SubmitSurvey/processSurveyResponse.ts
> -    country_id: countryId,
This isn't required in the central server

2023-11-19 21:51 UTC, tcaiger commented on packages/datatrak-web/src/views/LandingPage/RecentSurveysSection.tsx
> -  const handleSelectSurvey = async (surveyCode: string, countryId: string) => {
This is no longer needed as the countryId is checked and updated in the survey page now

2023-11-19 22:30 UTC, acdunham approved these changes
Thanks for those changes!

2023-11-19 22:37 UTC, merged